In [1]:
import pandas as pd
from pathlib import Path
import re

from pathlib import Path

csv_path = Path("title_cols.csv")
df = pd.read_csv(csv_path)

In [2]:
df["use"].value_counts()

use
vase                  1132
storage               1102
pouring                870
flask_and_bottle       658
wine_alcohol_water     198
other                  125
animal_shaped           60
ritual                  39
Name: count, dtype: int64

In [3]:
vc = df["use"].fillna("").replace("", "(empty)").value_counts()
pd.DataFrame({"count": vc, "pct": (vc / len(df) * 100).round(1)})

                    count   pct
use
vase                 1132  27.1
storage              1102  26.3
pouring               870  20.8
flask_and_bottle      658  15.7
wine_alcohol_water    198   4.7
other                 125   3.0
animal_shaped          60   1.4
ritual                 39   0.9

In [4]:
# treat NaN, "", and whitespace-only as empty
u = df["use"]
empty_mask = u.isna() | u.astype(str).str.strip().eq("")

df_empty = df[empty_mask]
df_empty

Empty DataFrame
Columns: [objectID, title, use]
Index: []

In [5]:
df_empty.iloc[60:80]  # or .iloc[i:i+100] and step through

Empty DataFrame
Columns: [objectID, title, use]
Index: []

In [6]:
u = df["use"]
empty = u.isna() | u.astype(str).str.strip().eq("")
df.loc[empty & df["title"].str.contains("spout", case=False, na=False)]

Empty DataFrame
Columns: [objectID, title, use]
Index: []