In [1]:
from pathlib import Path
import json
import pandas as pd
import numpy as np
import re

In [2]:
# objects.json is always next to this notebook
data_path = Path("objects.json")
with data_path.open("r", encoding="utf-8") as f:
  raw = json.load(f)

In [3]:
df = pd.DataFrame.from_dict(raw, orient="index").reset_index(drop=True)

In [4]:
df.shape

(4200, 54)

In [5]:
df.columns

Index(['objectID', 'isHighlight', 'accessionNumber', 'accessionYear',
       'isPublicDomain', 'primaryImage', 'primaryImageSmall',
       'additionalImages', 'constituents', 'department', 'objectName', 'title',
       'culture', 'period', 'objectDate', 'objectBeginDate', 'objectEndDate',
       'medium', 'dimensions', 'measurements', 'creditLine', 'classification',
       'metadataDate', 'repository', 'objectURL', 'tags', 'isTimelineWork',
       'objectWikidata_URL', 'GalleryNumber', 'artistRole',
       'artistDisplayName', 'artistDisplayBio', 'artistAlphaSort',
       'artistNationality', 'artistBeginDate', 'artistEndDate',
       'artistWikidata_URL', 'artistULAN_URL', 'artistPrefix', 'country',
       'geographyType', 'state', 'region', 'city', 'river', 'artistSuffix',
       'dynasty', 'subregion', 'locale', 'locus', 'excavation', 'reign',
       'county', 'artistGender'],
      dtype='object')

In [6]:
df.head()

,objectID,isHighlight,accessionNumber,accessionYear,isPublicDomain,primaryImage,primaryImageSmall,additionalImages,constituents,department,...,river,artistSuffix,dynasty,subregion,locale,locus,excavation,reign,county,artistGender
0,44793,False,50.61.11,1950,True,https://images.metmuseum.org/CRDImages/as/orig...,https://images.metmuseum.org/CRDImages/as/web-...,[],None,Asian Art,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,44817,False,1975.268.185,1975,True,https://images.metmuseum.org/CRDImages/as/orig...,https://images.metmuseum.org/CRDImages/as/web-...,[https://images.metmuseum.org/CRDImages/as/ori...,None,Asian Art,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,44830,False,1975.268.378,1975,True,https://images.metmuseum.org/CRDImages/as/orig...,https://images.metmuseum.org/CRDImages/as/web-...,[],None,Asian Art,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,44862,False,1975.268.473,1975,True,https://images.metmuseum.org/CRDImages/as/orig...,https://images.metmuseum.org/CRDImages/as/web-...,[https://images.metmuseum.org/CRDImages/as/ori...,None,Asian Art,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,44907,False,1975.268.376,1975,True,https://images.metmuseum.org/CRDImages/as/orig...,https://images.metmuseum.org/CRDImages/as/web-...,[],None,Asian Art,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# If your column is named differently, replace "classification" below.
col = "classification"

# Normalize blanks to NA first
s = (
    df[col]
    .astype("string")
    .str.strip()
    .replace("", pd.NA)
)

# Overall coverage
pct_has_classification = s.notna().mean() * 100
print(f"Rows with classification: {s.notna().sum()} / {len(df)} ({pct_has_classification:.2f}%)")

# Per-classification counts + percent of all rows
classification_summary = (
    s.fillna("MISSING")
    .value_counts(dropna=False)
    .rename_axis(col)
    .reset_index(name="count")
)

classification_summary["percent_of_all_rows"] = (
    classification_summary["count"] / len(df) * 100
).round(2)

classification_summary

Rows with classification: 4098 / 4200 (97.57%)

              classification  count  percent_of_all_rows
0                   Ceramics   2548                60.67
1        Ceramics-Containers    524                12.48
2           Ceramics-Pottery    427                10.17
3         Ceramics-Porcelain    297                 7.07
4                      Vases    257                 6.12
5                    MISSING    102                 2.43
6  Ceramics-Porcelain-Export     32                 0.76
7           Ceramics-Vessels      8                 0.19
8           Ceramics-Faience      3                 0.07
9                Terracottas      2                 0.05

In [8]:
missing_classification_rows = (
    df.loc[
        df["classification"].astype("string").str.strip().isna()
        | (df["classification"].astype("string").str.strip() == ""),
        ["department", "objectID", "title"],
    ]
    .sort_values(["department", "objectID"])
    .reset_index(drop=True)
)

# show every row/column in notebook output
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", None):
    display(missing_classification_rows)

,department,objectID,title
0,Ancient West Asian Art,891616,Jug with Assyrian-inspired decoration
1,Ancient West Asian Art,891620,Jug with Assyrian-inspired decoration
2,Egyptian Art,545042,Tell el-Yahudiya type juglet
3,Egyptian Art,545772,Classic Kerma Beaker
4,Egyptian Art,545791,Two-handed pottery vase of Amenhotep
5,Egyptian Art,546034,Black-topped red ware jar
6,Egyptian Art,546649,Jar
7,Egyptian Art,546758,White cross-lined ware beaker with hippos
8,Egyptian Art,546986,Cypriot ring-based Juglet
9,Egyptian Art,547254,Jar Decorated with Boats
10,Egyptian Art,547274,White cross-lined ware beaker with Nile River scene
11,Egyptian Art,547452,Spouted vessel in decorated ware
12,Egyptian Art,547504,Wavy-handled jar
13,Egyptian Art,547523,Vessel in shape of bird
14,Egyptian Art,547756,Jar
15,Egyptian Art,549136,Canopic Jar of Ruiu
16,Egyptian Art,549140,Two-Handled Jar from the Burial
17,Egyptian Art,551026,Beaker
18,Egyptian Art,551028,Beaker
19,Egyptian Art,551843,Black-topped Red Ware Beaker
20,Egyptian Art,551844,Black-topped Red Ware Beaker
21,Egyptian Art,551845,Black-topped red ware beaker
22,Egyptian Art,552174,Decorated ware jar with vertical bands of wavy lines
23,Egyptian Art,552180,Black-topped red ware cylindrical jar
24,Egyptian Art,552190,Polished red ware jar with lugs
25,Egyptian Art,552353,Pot That Contained a Donkey (12.181.272b-k)
26,Egyptian Art,554326,Pot
27,Egyptian Art,554515,Black-topped Red Ware Beaker
28,Egyptian Art,558198,White cross-lined ware beaker with geometric and floral design
29,Egyptian Art,558204,Black-topped red ware beaker
30,Egyptian Art,558282,Marl ware jar with lug handles
31,Egyptian Art,569685,Vessel in the shape of a horse
32,Egyptian Art,572220,Canopic Jar with an Image Representing the Hieroglyph for Face
33,Egyptian Art,576327,Pot
34,The American Wing,2292,Covered bean pot
35,The American Wing,2432,Covered Pitcher
36,The American Wing,2473,Covered slop jar
37,The American Wing,2539,Tobacco Jar
38,The American Wing,2561,Covered Vase
39,The American Wing,2635,Cream Pitcher
40,The American Wing,2636,Cream Pitcher
41,The American Wing,2647,Creamer
42,The American Wing,2737,Creamer
43,The American Wing,3463,Apothecary Jar
44,The American Wing,3469,Apothecary Jar
45,The American Wing,3561,Ewer
46,The American Wing,3563,Ewer
47,The American Wing,3761,Flower Pot
48,The American Wing,3992,Cream Pitcher
49,The American Wing,4480,Chamber Pot
50,The American Wing,4508,Barrel
51,The American Wing,4585,Jug
52,The American Wing,4895,Vase
53,The American Wing,5397,Mustard Pot
54,The American Wing,5667,Pitcher
55,The American Wing,5698,Pitcher
56,The American Wing,5726,Pitcher
57,The American Wing,5732,Pitcher
58,The American Wing,5737,Pitcher
59,The American Wing,5762,Pitcher
60,The American Wing,5769,Pitcher
61,The American Wing,5783,Pitcher
62,The American Wing,5848,Pitcher
63,The American Wing,5850,Pitcher
64,The American Wing,5853,Pitcher
65,The American Wing,5860,Pitcher
66,The American Wing,7740,Spill Vase
67,The American Wing,7742,Spill Vase
68,The American Wing,8048,Syrup Jug
69,The American Wing,8681,Toddy Jug
70,The American Wing,9199,Flower Pot
71,The American Wing,9202,Vase
72,The American Wing,9214,Vase
73,The American Wing,9242,Vase
74,The American Wing,9246,Vase
75,The American Wing,9248,Vase
76,The American Wing,9257,Vase
77,The American Wing,9284,Vase
78,The American Wing,9286,Vase
79,The American Wing,9336,Vase
80,The American Wing,9353,Vase
81,The American Wing,9386,Vase
82,The American Wing,9506,Vase
83,The American Wing,9579,Vase
84,The American Wing,9582,Covered Vase
85,The American Wing,9584,Covered Vase
86,The American Wing,9752,Water Bottle
87,The American Wing,13455,Ewer
88,The American Wing,14371,Pitcher
89,The American Wing,14828,Covered potpourri vase
90,The American Wing,15595,Vase
91,The American Wing,16298,Pitcher
92,The American Wing,16544,Vase
93,The American Wing,17732,Vase
94,The American Wing,18861,Pitcher
95,The American Wing,19001,Covered honey pot
96,The American Wing,19071,Vase
97,The American Wing,19827,Pilgrim vase
98,The American Wing,20076,Vase
99,The American Wing,20637,Pitcher
100,The American Wing,20730,Pitcher
101,The American Wing,716908,Vase

In [9]:
target_classification = "Ceramics-Porcelain-Export"

rows = (
    df.loc[
        df["classification"].astype("string").str.strip() == target_classification,
        ["department", "objectID", "title"],
    ]
    .sort_values(["department", "objectID"])
    .reset_index(drop=True)
)

# show all rows
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", None):
    display(rows)

,department,objectID,title
0,European Sculpture and Decorative Arts,185900,Puzzle jug
1,European Sculpture and Decorative Arts,185901,Vase
2,European Sculpture and Decorative Arts,185902,Jug with cover
3,European Sculpture and Decorative Arts,185914,Jug with cover
4,European Sculpture and Decorative Arts,194624,Pitcher with cover
5,European Sculpture and Decorative Arts,195127,Jug
6,European Sculpture and Decorative Arts,195307,Jug
7,European Sculpture and Decorative Arts,200670,Vase
8,European Sculpture and Decorative Arts,201054,Milk jug with cover
9,European Sculpture and Decorative Arts,201289,Cream jug
10,European Sculpture and Decorative Arts,201290,Wall vase
11,European Sculpture and Decorative Arts,201299,Hot milk jug
12,European Sculpture and Decorative Arts,202473,Vase with cover
13,European Sculpture and Decorative Arts,202581,Jug with Portuguese arms
14,European Sculpture and Decorative Arts,202967,Jar with cover
15,European Sculpture and Decorative Arts,204098,Cream jug
16,European Sculpture and Decorative Arts,206796,Ewer
17,European Sculpture and Decorative Arts,206914,Bottle
18,European Sculpture and Decorative Arts,207404,Ewer
19,European Sculpture and Decorative Arts,207745,Ewer
20,European Sculpture and Decorative Arts,208243,Bottle
21,European Sculpture and Decorative Arts,208245,Ewer
22,European Sculpture and Decorative Arts,208248,Jar
23,European Sculpture and Decorative Arts,208279,Bottle with flowers of the four seasons
24,European Sculpture and Decorative Arts,208307,Ewer
25,European Sculpture and Decorative Arts,208389,Bottle
26,European Sculpture and Decorative Arts,208397,Vase
27,European Sculpture and Decorative Arts,208398,Vase
28,European Sculpture and Decorative Arts,208421,Vase
29,European Sculpture and Decorative Arts,623471,Baluster-shaped vase
30,European Sculpture and Decorative Arts,623500,Covered jar with large finial
31,European Sculpture and Decorative Arts,680974,Jar with the emblem of the Order of Saint Augustine

### Map
Possible columns:
- department
- culture
- country
- state
- region
- city
- geographyType

In [10]:
cols_to_check = [
    "department",
    "culture",
    "country",
    "state",
    "region",
    "city",
    "geographyType",
    "artistNationality",
]

results = []

for col in cols_to_check:
    s = df[col]

    # Start with nulls
    missing = s.isna()

    # For string-like values, also treat blank/whitespace/"undefined" as missing
    s_str = s.astype("string").str.strip()
    missing = missing | s_str.eq("") | s_str.str.lower().eq("undefined")

    present = ~missing

    total = len(s)
    present_count = int(present.sum())
    missing_count = int(missing.sum())

    results.append({
        "column": col,
        # "present_count": present_count,
        # "missing_count": missing_count,
        "present_pct": round(present_count / total * 100, 2),
        # "missing_pct": round(missing_count / total * 100, 2),
    })

summary = pd.DataFrame(results).sort_values("present_pct", ascending=False)
summary

              column  present_pct
0         department       100.00
1            culture        73.79
2            country        26.71
6      geographyType        14.17
7  artistNationality        10.48
5               city         7.98
4             region         5.19
3              state         4.88

In [11]:
# Count of rows per department
department_counts = (
    df["department"]
    .fillna("<<MISSING_DEPARTMENT>>")
    .astype("string")
    .str.strip()
    .replace("", "<<MISSING_DEPARTMENT>>")
    .value_counts(dropna=False)
)

# department_counts

department_summary = pd.DataFrame({
    "count": department_counts,
    "percent": (department_counts / department_counts.sum() * 100).round(2)
})

department_summary

                                        count  percent
department
Asian Art                                1998    47.57
European Sculpture and Decorative Arts    690    16.43
The Michael C. Rockefeller Wing           531    12.64
Islamic Art                               371     8.83
Greek and Roman Art                       259     6.17
Medieval Art                              128     3.05
Robert Lehman Collection                   76     1.81
The American Wing                          68     1.62
The Cloisters                              34     0.81
Egyptian Art                               32     0.76
Modern and Contemporary Art                11     0.26
Ancient West Asian Art                      2     0.05

In [12]:
# For each department, compute % present for every column in cols_to_check

def is_present(series: pd.Series) -> pd.Series:
    s = series.astype("string").str.strip()
    return series.notna() & s.ne("") & s.str.lower().ne("undefined")

# Clean department labels for grouping
dept_series = (
    df["department"]
    .fillna("<<MISSING_DEPARTMENT>>")
    .astype("string")
    .str.strip()
    .replace("", "<<MISSING_DEPARTMENT>>")
)

# Build a table: rows = department, cols = indicators for presence
out = pd.DataFrame({"department": dept_series})

for col in cols_to_check:
    out[f"{col}_present"] = is_present(df[col]).astype(int)

dept_present_pct = (
    out.groupby("department")[[f"{c}_present" for c in cols_to_check]]
    .mean()
    .mul(100)
    .round(0)
)

# rename "country_present" -> "country", etc.
dept_present_pct.columns = [c.replace("_present", "") for c in dept_present_pct.columns]

# add total rows per department
dept_counts = out.groupby("department").size().rename("total_count")
dept_present_pct = dept_present_pct.join(dept_counts)

# optional: show count first
dept_present_pct = dept_present_pct[["total_count"] + cols_to_check]

dept_present_pct

,total_count,department,culture,country,state,region,city,geographyType,artistNationality
department,,,,,,,,,
Ancient West Asian Art,2,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
Asian Art,1998,100.0,100.0,0.0,0.0,0.0,0.0,0.0,2.0
Egyptian Art,32,100.0,0.0,97.0,0.0,53.0,0.0,100.0,0.0
European Sculpture and Decorative Arts,690,100.0,0.0,0.0,0.0,0.0,0.0,0.0,52.0
Greek and Roman Art,259,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
Islamic Art,371,100.0,0.0,100.0,0.0,0.0,62.0,100.0,0.0
Medieval Art,128,100.0,100.0,73.0,63.0,0.0,21.0,74.0,0.0
Modern and Contemporary Art,11,100.0,45.0,0.0,0.0,0.0,0.0,0.0,100.0
Robert Lehman Collection,76,100.0,99.0,0.0,0.0,0.0,0.0,0.0,1.0
The American Wing,68,100.0,99.0,99.0,74.0,74.0,71.0,99.0,46.0
The Cloisters,34,100.0,100.0,91.0,79.0,0.0,76.0,91.0,0.0
The Michael C. Rockefeller Wing,531,100.0,100.0,100.0,9.0,28.0,1.0,0.0,0.0

Findings:
- 100% have "department"
- 71.10% have "culture"
- 25.12% have "country"


Location by department:
- Asian Art: culture
- European Sculpture and Decorative Arts: artistNationality
- Islamic Art: city, country
- Medieval Art: city, state, country, culture
- Modern and Contemporary Art: culture, artistNationality
- Robert Lehman Collection: culture, artistNationality
- The Cloisters: city, state, country, culture
- The Michael C. Rockefeller Wing: city, state, country, culture

In [13]:
# Make a copy
df_loc = df.copy()

def clean_missing(s: pd.Series) -> pd.Series:
    s = s.astype("string").str.strip()
    return s.mask(s.eq("") | s.str.lower().eq("undefined"))

# Department -> ordered source columns for location
location_priority = {
    "Asian Art": ["culture"],
    "European Sculpture and Decorative Arts": ["artistNationality"],
    "Islamic Art": ["city", "country"],
    "Medieval Art": ["city", "state", "country", "culture"],
    "Modern and Contemporary Art": ["culture", "artistNationality"],
    "Robert Lehman Collection": ["culture", "artistNationality"],
    "The Cloisters": ["city", "state", "country", "culture"],
    "The Michael C. Rockefeller Wing": ["city", "state", "country", "culture"],
    "Egyptian Art": ["country", "region"],
    "Greek and Roman Art": ["culture"]
}

# Start empty
df_loc["location"] = pd.NA

# Fill location by department using first non-missing column in priority order
for dept, cols in location_priority.items():
    mask = df_loc["department"].eq(dept)
    if not mask.any():
        continue

    # build first-non-missing across preferred columns
    candidates = pd.DataFrame({c: clean_missing(df_loc.loc[mask, c]) for c in cols})
    df_loc.loc[mask, "location"] = candidates.bfill(axis=1).iloc[:, 0]

# quick check
# df_loc[["department", "culture", "artistNationality", "city", "state", "country", "location"]].head(20)

In [14]:
# How many got location per listed department
check = (
    df_loc[df_loc["department"].isin(location_priority)]
    .assign(location_present=lambda d: d["location"].notna())
    .groupby("department")["location_present"]
    .mean()
    .mul(100)
    .round(2)
    .sort_values(ascending=False)
)
check

department
Asian Art                                 100.00
Egyptian Art                              100.00
European Sculpture and Decorative Arts    100.00
Greek and Roman Art                       100.00
Medieval Art                              100.00
Modern and Contemporary Art               100.00
Robert Lehman Collection                  100.00
The Cloisters                             100.00
The Michael C. Rockefeller Wing           100.00
Islamic Art                                99.73
Name: location_present, dtype: float64

In [15]:
location_counts = (
    df_loc["location"]
    .fillna("<<MISSING_LOCATION>>")
    .astype("string")
    .str.strip()
    .replace("", "<<MISSING_LOCATION>>")
    .value_counts(dropna=False)
)

location_summary = pd.DataFrame({
    # "count": location_counts,
    "percent": (location_counts / location_counts.sum() * 100).round(2)
})

location_summary

                                percent
location
China                             30.21
Japan                             13.86
Peru                              10.21
British                            7.57
French                             4.05
...                                 ...
French (Limoges)                   0.02
Wiltshire                          0.02
Tembladera                         0.02
Italian, possibly Tuscany          0.02
Greek, South Italian, Gnathian     0.02

[199 rows x 1 columns]

In [16]:
n_unique_locations = (
    df_loc["location"]
    .fillna("")
    .astype("string")
    .str.strip()
    .replace("", "")
    .nunique(dropna=False)
)

print(f"Number of different locations: {n_unique_locations:,}")

Number of different locations: 199

In [17]:
all_locations = (
    df_loc["location"]
    .fillna("")
    .astype("string")
    .str.strip()
    .replace("", "")
    .drop_duplicates()
    .sort_values()
    .tolist()
)

all_locations

['',
 'Abu Mena',
 'Alta Verapaz',
 'American',
 'American and French',
 'Ancash',
 'Arizona',
 'Bandiagara Escarpment',
 'Belgian',
 'Bohemian',
 'British',
 'British, Scottish',
 'Byzantine (Egypt)',
 'Canosan, Puglia',
 'Chiclayo',
 'Chihuahua',
 'China',
 'China (?)',
 'China or Japan (?)',
 'ChinaNeihuLu',
 'Chinese',
 'Cocle Province',
 'Colima',
 'Colombia',
 'Comala',
 'Ctesiphon',
 'Cycladic',
 'Cycladic or Cretan',
 'Cypriot',
 'Danish',
 'Danish (Nästved)',
 'Derbyshire',
 'Dutch',
 'Dutch (Delft)',
 'East Greek',
 'East Greek, Rhodian',
 'Eastern Syria',
 'Ecuador',
 'Egypt',
 'Egyptian',
 'Etruscan',
 'Etruscan, Etrusco-Corinthian',
 'Etruscan, Italo-Corinthian',
 'Europe',
 'European',
 'Faliscan',
 'Florence',
 'Florence or its vicinity',
 'French',
 'French (Limoges)',
 'French (Paris)',
 'Fustat',
 'German',
 'Greek',
 'Greek or Roman',
 'Greek, Asia Minor',
 'Greek, Attic',
 'Greek, Boeotian (or Attic)',
 'Greek, Chalcidian',
 'Greek, Corinthian',
 'Greek, Egypt, Alexandria-Hadra',
 'Greek, Laconian',
 'Greek, Ptolemaic',
 'Greek, Ptolemaic, Cretan',
 'Greek, Sicilian, Centuripe',
 'Greek, South Italian, Apulian',
 'Greek, South Italian, Apulian, Canosan',
 'Greek, South Italian, Campanian',
 'Greek, South Italian, Gnathian',
 'Greek, South Italian, Lucanian',
 'Greek, probably Corinthian',
 'Greek, probably Cypriot',
 'Guatemala',
 'Guatemala or Mexico',
 'Gurgan',
 'Helladic',
 'Helladic, Mycenaean',
 'India',
 'India, Bombay School',
 'Iran',
 'Iran or Iraq',
 'Iraq',
 'Iraq or Iran, Persian Gulf',
 'Iraq or Syria',
 'Irish',
 'Italian',
 'Italian (probably Naples)',
 'Italian (supposedly Faenza or Florence)',
 'Italian, Castelli',
 'Italian, Deruta',
 'Italian, Faenza',
 'Italian, Faenza or Florence',
 'Italian, Faenza or Naples',
 'Italian, Faenza or Pesaro',
 'Italian, Florence or vicinity',
 'Italian, Naples',
 'Italian, Tuscany, Cafaggiolo or Montelupo',
 'Italian, Urbino',
 'Italian, perhaps Trapani',
 'Italian, possibly Florence or Faenza',
 'Italian, possibly Tuscany',
 'Italian, probably Faenza',
 'Italian, probably Faenza (or Palermo)',
 'Italian, probably Florence or vicinity',
 'Italian, probably Gubbio',
 'Italian, probably Tuscany (?)',
 'Iznik',
 'Japan',
 'Kashan',
 'Kharga Oasis',
 'Kirman',
 'Korea',
 'Kufa',
 'Lazio',
 'London',
 'Lydian',
 'Mali',
 'Manises',
 'Maya',
 'Meuse Valley',
 'Mexico',
 'Mexico or Guatemala',
 'Michoacan',
 'Middle Egypt',
 'Middle Rhineland (?)',
 'Mill Green',
 'Minoan',
 'Montelupo',
 'Mycenaean',
 'Mycenaean or Cypro-Mycenaean',
 'Nayarit',
 'Netherlandish',
 'New Mexico',
 'Nishapur',
 'Nishapur or Samarqand',
 'North Coast',
 'Northeast China (Hongshan culture)',
 'Nubia (Sudan)',
 'Oaxaca',
 'Orvieto ?',
 'Panama',
 'Paris',
 'Paris or its vicinity',
 'Paterna',
 'Peru',
 'Phoenician',
 'Piura',
 'Potter Toynton (?)',
 'Puebla',
 'Qasr-i Abu Nasr',
 'Raqqa',
 'Rayy',
 'Roman',
 'Rome',
 'Russian',
 'Saintonge',
 'Santa Province',
 'Santa Province (?)',
 'Saveh',
 'Scarborough',
 'Siegburg',
 'Siena',
 'South Coast',
 'Spain',
 'Spain or North Africa',
 'Spanish',
 'Surrey',
 'Swiss',
 'Syria',
 'Tembladera',
 'Thailand',
 'Thailand (Ban Chiang culture)',
 'Thailand (Ban Chiang)',
 'Thailand (Buriram Province)',
 'Thailand (Si Satchanalai)',
 'Thebes',
 'Todi',
 'Turkey',
 'Tuscany',
 'Valencia',
 'Veracruz',
 'Vietnam',
 'Vietnam (North)',
 'Vietnam, Hong River region',
 'Visigothic',
 'Viterbo',
 'Wiltshire',
 'near Raqqa',
 'near Susa',
 'probably Basra',
 'probably Egypt',
 'probably Isfahan',
 'probably Kirman',
 'probably Manises',
 'probably Mashhad',
 'probably Orvieto',
 'probably Rayy',
 'probably Seville',
 'probably Surrey']

### Timeline
- objectBeginDate
- objectEndDate
- objectDate

In [18]:
date_cols = ["objectBeginDate", "objectEndDate", "objectDate"]

rows = []
for col in date_cols:
    s = df[col]
    s_str = s.astype("string").str.strip()
    present = s.notna() & s_str.ne("") & s_str.str.lower().ne("undefined")
    rows.append({
        "column": col,
        "present_count": int(present.sum()),
        "missing_count": int((~present).sum()),
        "present_pct": round(present.mean() * 100, 2),
    })

pd.DataFrame(rows)

            column  present_count  missing_count  present_pct
0  objectBeginDate           4200              0       100.00
1    objectEndDate           4200              0       100.00
2       objectDate           3830            370        91.19

In [19]:
b = pd.to_numeric(df["objectBeginDate"], errors="coerce")
e = pd.to_numeric(df["objectEndDate"], errors="coerce")

both_present = b.notna() & e.notna()
equal = both_present & (b == e)

n_total = len(df)
n_both = int(both_present.sum())
n_equal = int(equal.sum())

print(f"Rows where begin & end are both present:  ({n_both / n_total * 100:.2f}%)")
print(f"Rows where objectBeginDate == objectEndDate (and both present): ({n_equal / n_total * 100:.2f}%)")
# print(f"Among rows with both present: {n_equal / n_both * 100:.2f}%" if n_both else "Among rows with both present: n/a (no rows)")

Rows where begin & end are both present:  (100.00%)
Rows where objectBeginDate == objectEndDate (and both present): (6.40%)

In [20]:
df[date_cols].sample(n=min(20, len(df)), random_state=42)

      objectBeginDate  objectEndDate                    objectDate
1743             -500           -200           5th–3rd century BCE
2196             1695           1710                 ca. 1700–1705
1728             1300           1399                  14th century
3337             1622           1722                           NaN
298              1600           1699                  17th century
1837             1700           1799                  18th century
4016             1640           1660                      ca. 1650
351              1100           1299             12th–13th century
3315             1400           1599             15th–16th century
2458             1890           1900                      ca. 1895
1029             1568           1599             late 16th century
2319             1800           1899                  19th century
1477             1800           1815            early 19th century
3773             -425           -400          late 5th century BCE
2902             -775           -425           9th–4th century BCE
2292             1700           1799                  18th century
3571             1590           1610                      ca. 1600
497              1271           1368             13th–14th century
1995             1667           1733  late 17th–early 18th century
734              1750           1810      second half 18th century

In [21]:
df2 = df.copy()
b = pd.to_numeric(df2["objectBeginDate"], errors="coerce")
e = pd.to_numeric(df2["objectEndDate"], errors="coerce")
mid = ((b + e) / 2).where(b.notna() & e.notna())
df2["final_date"] = (mid // 1).where(mid.notna()).astype("Int64")

In [22]:
df2['final_date'].sample(n=min(20, len(df)), random_state=42)

1743    -350
2196    1702
1728    1349
3337    1672
298     1649
1837    1749
4016    1650
351     1199
3315    1499
2458    1895
1029    1583
2319    1849
1477    1807
3773    -413
2902    -600
2292    1749
3571    1600
497     1319
1995    1700
734     1780
Name: final_date, dtype: Int64

In [23]:
df2["final_date"].agg(["min", "max"])

min   -4250
max    1950
Name: final_date, dtype: int64

# Get Function

In [24]:
# Normalize objectName first
obj_name = (
    df["objectName"]
    .astype("string")
    .str.strip()
    .replace("", pd.NA)
)

objectname_summary = (
    obj_name.fillna("MISSING")
    .value_counts(dropna=False)
    .rename_axis("objectName")
    .reset_index(name="count")
)

objectname_summary["percent"] = (
    objectname_summary["count"] / len(df) * 100
).round(2)

# Show all distinct values with count + percent
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", None):
    display(objectname_summary)

                                           objectName  count  percent
0                                                Vase   1136    27.05
1                                              Bottle    720    17.14
2                                                 Jar    564    13.43
3                                                 Jug    246     5.86
4                                                Ewer    210      5.0
5                                             Tea jar     94     2.24
6                                              Vessel     80      1.9
7                                         Covered jar     78     1.86
8                                             Pitcher     59      1.4
9                                         Bottle vase     47     1.12
10                                          Albarello     39     0.93
11                                    Vase with cover     39     0.93
12                                       Pharmacy jar     39     0.93
13                                        Wine bottle     34     0.81
14                                     Jar with cover     34     0.81
15                                       Scent bottle     31     0.74
16                                          Cream jug     28     0.67
17                                         Moon flask     28     0.67
18                                          Water jar     26     0.62
19                                            Amphora     25      0.6
20                                           Lekythos     22     0.52
21                                        Sake bottle     16     0.38
22                                           Oinochoe     16     0.38
23                                              Flask     15     0.36
24                                        Storage jar     14     0.33
25                                       Neck-amphora     14     0.33
26                                                Pot     14     0.33
27                                     Pilgrim bottle     13     0.31
28                                                Urn     13     0.31
29                                          Water pot     11     0.26
30                                        Flower vase     10     0.24
31                                       Water bottle     10     0.24
32                                             Juglet      9     0.21
33                                         Oil bottle      9     0.21
34                                     Jug with cover      8     0.19
35                                     Squat lekythos      7     0.17
36                                      Pilgrim flask      7     0.17
37                                             Beaker      7     0.17
38                                        Amphoriskos      6     0.14
39                                         Alabastron      6     0.14
40                                 Tea jar with cover      6     0.14
41                         Freshwater jar (mizusashi)      6     0.14
42                                     Hydria, kalpis      6     0.14
43                                Milk jug with cover      6     0.14
44                                       Hanging vase      6     0.14
45                                     Potpourri vase      5     0.12
46                                      Hydria, Hadra      5     0.12
47                            Pharmacy jar with cover      5     0.12
48                                           Toby jug      5     0.12
49                                         Puzzle jug      5     0.12
50                                  Apothecary bottle      5     0.12
51                                      Vase with lid      5     0.12
52                                           Milk jug      5     0.12
53                                     Apothecary jar      5     0.12
54                                   False-necked jar      4      0.1
55                                         Flower pot      4      0.1
56                                       Jar with lid      4      0.1
57                                       Covered ewer      4      0.1
58                                       Hot milk jug      4      0.1
59                                    Oinochoe, chous      4      0.1
60                                      Square bottle      4      0.1
61                                      Bottle cooler      4      0.1
62                                         Spill vase      4      0.1
63                                    Apothecary vase      4      0.1
64                                          Wall vase      4      0.1
65                                             Pelike      4      0.1
66                     Askos in the form of an animal      3     0.07
67                                           Wine jar      3     0.07
68                                    Ewer with cover      3     0.07
69                                          Wine ewer      3     0.07
70                                Milk pot with cover      3     0.07
71                                         Lidded jar      3     0.07
72                                    Amphora, Type B      3     0.07
73                              Toilet jar with cover      3     0.07
74                                      Cream pitcher      3     0.07
75                               Beaker, black topped      3     0.07
76                                             Guttus      3     0.07
77             Nolan neck-amphora with triple handles      3     0.07
78                                    Amphora, Type A      3     0.07
79                                      Jar and cover      3     0.07
80                                             Hydria      3     0.07
81                                    Vessel with lid      3     0.07
82                                        Harvest jug      2     0.05
83                                          Cream pot      2     0.05
84                                      Minature vase      2     0.05
85                                       Funerary urn      2     0.05
86                                       Loutrophoros      2     0.05
87                                         Toilet jar      2     0.05
88                          Pilgrim bottle with cover      2     0.05
89                                           Milk pot      2     0.05
90                                              Askos      2     0.05
91                                     Spindle bottle      2     0.05
92                        Askos in the form of a duck      2     0.05
93                                           Strainer      2     0.05
94                                     Freshwater jar      2     0.05
95                                    Vase, miniature      2     0.05
96                                             Krater      2     0.05
97                                       Square flask      2     0.05
98                                 Jug, barrel-shaped      2     0.05
99                Rhyton in the form of a deer's head      2     0.05
100                                Nolan neck-amphora      2     0.05
101                                         Aryballos      2     0.05
102                                         Epichysis      2     0.05
103                                       Pithoid jar      2     0.05
104                                            Situla      2     0.05
105                                           Stamnos      2     0.05
106                                 Vase with stopper      2     0.05
107                                      Covered vase      2     0.05
108                                     Rosewater jug      2     0.05
109                                      Pedestal jar      2     0.05
110                               Hanging flower vase      2     0.05
111                                      Perfume vase      2     0.05
112                                         Syrup jug      2     0.05
113                                        Footed urn      2     0.05
114                               Bottle with stopper      2     0.05
115                                          Wine pot      2     0.05
116                                        Book flask      2     0.05
117                                         Water Jar      2     0.05
118                                          Gallipot      2     0.05
119                                       Lidded vase      2     0.05
120                                         Water jug      2     0.05
121                                Wine ewer with lid      2     0.05
122                                         Honey pot      1     0.02
123                  Aryballos in the form of a siren      1     0.02
124                        Vase in the form of a fish      1     0.02
125                                       Stirrup jar      1     0.02
126                                        Funnel-jar      1     0.02
127                                  Covered Lime pot      1     0.02
128                                     Lebes gamikos      1     0.02
129                                       Mustard pot      1     0.02
130                                       Storage Jar      1     0.02
131                                      Urn with lid      1     0.02
132                                          Nestoris      1     0.02
133                                       Neck-pelike      1     0.02
134                                Amphora, miniature      1     0.02
135                                         Toddy jug      1     0.02
136                    Ampulla (Flask) of Saint Menas      1     0.02
137                                 Krater, miniature      1     0.02
138                                    Jar, miniature      1     0.02
139                         Vase in the form of a pig      1     0.02
140                                 Hydria, miniature      1     0.02
141                                        Ginger jar      1     0.02
142                      Vase with strainer and spout      1     0.02
143                 Alabastron in the form of a woman      1     0.02
144  Vase in the form of a sleeping black African boy      1     0.02
145                  Alabastron in the form of a hare      1     0.02
146                      Vase in the form of a basket      1     0.02
147                 Neck-amphora with twisted handles      1     0.02
148                                        Pen washer      1     0.02
149          Aryballos in the form of a helmeted head      1     0.02
150                      Vase in the form of a monkey      1     0.02
151                                          Kalathos      1     0.02
152                               Oinochoe, miniature      1     0.02
153                                     Globular vase      1     0.02
154                                  Amphora with lid      1     0.02
155                                     Volute-krater      1     0.02
156                                               Oon      1     0.02
157                               Water pot and cover      1     0.02
158                       Askos in the form of a bull      1     0.02
159                                    Beaker, hippos      1     0.02
160                          Juglet, Tell el-Yahudiya      1     0.02
161                      Vase, Amenhotep, two handled      1     0.02
162                            Jar, red polished ware      1     0.02
163                            Vessel, horse or camel      1     0.02
164                                   Jar, wavy lines      1     0.02
165                               Vessel, bird-shaped      1     0.02
166                               Jar, Decorated ware      1     0.02
167                              Spheroconical Vessel      1     0.02
168                                          Bean pot      1     0.02
169                                      Pilgrim vase      1     0.02
170                                          Slop jar      1     0.02
171                                       Tobacco jar      1     0.02
172                                     Column-krater      1     0.02
173               Rhyton in the form of a lamb's head      1     0.02
174                                       Askos, ring      1     0.02
175                 Neck-amphora of Panathenaic shape      1     0.02
176                                            Lydion      1     0.02
177                                           Kyathos      1     0.02
178                   Vessel, decorated ware, spouted      1     0.02
179                              Beaker, black-topped      1     0.02
180                     Beaker, Black-topped red ware      1     0.02
181                                   Flask, globular      1     0.02
182                     Vase, funerary, wedding scene      1     0.02
183                                      Calyx-krater      1     0.02
184                                       Ring-kernos      1     0.02
185                       Jug in the form of Dionysos      1     0.02
186                                    Jug, sauceboat      1     0.02
187                                   Aryballos, ring      1     0.02
188                                         Plemochoe      1     0.02
189                   Aryballos in the form of a bird      1     0.02
190                                            Bucket      1     0.02
191                  Canopic jar, human head, bearded      1     0.02
192                             Beaker, classic Kerma      1     0.02
193  Beaker, white cross-lined ware, Nile River scene      1     0.02
194                                 Jar, black topped      1     0.02
195                                 Jar, Wavy-handled      1     0.02
196                        Jar, decorated ware, boats      1     0.02
197                       Juglet, Cypriot, ring based      1     0.02
198                            Jar, two-handled, Ruiu      1     0.02
199                    Beaker, white cross-lined ware      1     0.02
200                                      Globular jar      1     0.02
201                                        Footed jar      1     0.02
202                                              Kero      1     0.02
203                                           Ampulla      1     0.02
204                             Writer's water bottle      1     0.02
205                           Storage or pharmacy jar      1     0.02
206                                         Sake ewer      1     0.02
207                                          Cake jar      1     0.02
208                                          Wine jug      1     0.02
209                                   Pharmacy bottle      1     0.02
210                               Gourd-shaped bottle      1     0.02
211                                      Milk pitcher      1     0.02
212                           Hot milk jug with cover      1     0.02
213                                       Mosque lamp      1     0.02
214                                Pitcher with cover      1     0.02
215                                      Snuff bottle      1     0.02
216                                      Baluster jar      1     0.02
217                                        Pomade pot      1     0.02
218                                       Covered pot      1     0.02
219                                  Bottle and cover      1     0.02
220                                        Ring flask      1     0.02
221                                       Double vase      1     0.02
222                                      Meiping vase      1     0.02
223                           Pharmacy or storage jar      1     0.02
224                                    Figural vessel      1     0.02
225                     Pilgrim bottle with screw top      1     0.02
226                                      Pharmacy Jar      1     0.02
227                             Milk or hot water jug      1     0.02
228                             Pomade pot with cover      1     0.02
229                                       Wine vessel      1     0.02
230                                        Bottle jug      1     0.02
231                                      Mortuary urn      1     0.02
232                                     Hot water jug      1     0.02
233                                           Brazier      1     0.02
234                                Miniature orb vase      1     0.02
235                                 Bottle with cover      1     0.02
236                                      Funerary jar      1     0.02
237                                    Miniature vase      1     0.02
238                                Jar or Fire-holder      1     0.02
239                                        Aquamanile      1     0.02
240                                      Hot milk pot      1     0.02
241                             Water bottle or flask      1     0.02
242                                     Puzzle bottle      1     0.02
243                                     Covered flask      1     0.02
244                                        Pomade jar      1     0.02
245                                            Censer      1     0.02
246                                  Jug, side-beaked      1     0.02
247               Askos in the form of a lobster claw      1     0.02
248                                   Minature bottle      1     0.02
249                                    Urn with cover      1     0.02
250                                     Water pitcher      1     0.02
251                                Flask, head-shaped      1     0.02
252                              Miniature moon flask      1     0.02
253                                      Vase, relief      1     0.02
254                                    Flask, lentoid      1     0.02
255                                    Jug, miniature      1     0.02
256                                    Perfume bottle      1     0.02
257                                        Saltcellar      1     0.02
258                        Vase in the form of a bird      1     0.02
259                      Juglet in the form of a horn      1     0.02
260                          Nicosthenic neck-amphora      1     0.02
261                                           Aidoion      1     0.02
262                             Neck-amphora with lid      1     0.02
263                                             Kendi      1     0.02
264                                    Apothecary jug      1     0.02
265                                    Cong-form vase      1     0.02
266                              Hand warmer or flask      1     0.02
267                                      Glass cooler      1     0.02
268                                    Jar with Cover      1     0.02
269                          Potpourri jar with cover      1     0.02
270                                         Cider jug      1     0.02
271                                       Vase or jar      1     0.02
272                           Holder for magic straws      1     0.02
273                                             Caddy      1     0.02
274                                      Brush holder      1     0.02
275                                        Clock vase      1     0.02
276                                    Spherical vase      1     0.02
277                              Covered water vessel      1     0.02
278               Canopic Jar, Ruiu, human head, Hapy      1     0.02
279                                     Potpourri jar      1     0.02
280                              Hydria, Hadra (foot)      1     0.02
281                               Bottle with handles      1     0.02
282                                      Watering pot      1     0.02
283                                               jar      1     0.02

In [25]:
df["objectName"].astype("string").str.strip().replace("", pd.NA).notna().mean() * 100

np.float64(100.0)

In [30]:
# Normalize objectName first
title = (
    df["title"]
    .astype("string")
    .str.strip()
    .replace("", pd.NA)
)

title_summary = (
    title.fillna("MISSING")
    .value_counts(dropna=False)
    .rename_axis("title")
    .reset_index(name="count")
)

title_summary["percent"] = (
    title_summary["count"] / len(df) * 100
).round(2)

# Show all distinct values with count + percent
with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", None):
    display(title_summary)

,title,count,percent
0,Vase,574,13.67
1,Jar,294,7.0
2,Bottle,226,5.38
3,Jug,184,4.38
4,Ewer,145,3.45
5,Tea Jar,58,1.38
6,Pitcher,55,1.31
7,Vase with cover,35,0.83
8,Covered Jar,35,0.83
9,Tea jar,33,0.79
10,Bottle vase,33,0.79
11,Meiping vase,33,0.79
12,Cream jug,28,0.67
13,Pharmacy Jar,27,0.64
14,Scent bottle,23,0.55
15,Double Spout and Bridge Bottle with Bird,20,0.48
16,Jar (Guan),20,0.48
17,Vase with birds and flowers,19,0.45
18,Apothecary jar (albarello),18,0.43
19,Jar with Cover,16,0.38
20,Amphora,16,0.38
21,Spheroconical Vessel,16,0.38
22,Wine Bottle,16,0.38
23,Albarello,16,0.38
24,Wine bottle,13,0.31
25,Vase with flowers,13,0.31
26,Jar with cover,12,0.29
27,Water Jar,12,0.29
28,Storage jar,11,0.26
29,Stirrup Spout Bottle with Figure,11,0.26
30,Terracotta jug,11,0.26
31,Stirrup Spout Bottle,11,0.26
32,Stirrup Spout Bottle with Couple,11,0.26
33,Double Spout Bottle,10,0.24
34,Lekythos,10,0.24
35,Bottle vase with floral scrolls,9,0.21
36,Terracotta oinochoe (jug),9,0.21
37,Pharmacy jar (albarello),9,0.21
38,Vase with floral scrolls,9,0.21
39,Terracotta neck-amphora (jar),9,0.21
40,Flask,8,0.19
41,Small vase,8,0.19
42,Pot,8,0.19
43,Juglet,8,0.19
44,Terracotta lekythos (oil flask),8,0.19
45,Vase with landscape,7,0.17
46,Water pot,7,0.17
47,Pilgrim bottle,7,0.17
48,Vase with dragon,7,0.17
49,Miniature vase,7,0.17
50,Hanging Vase,7,0.17
51,Vessel,7,0.17
52,Oinochoe,7,0.17
53,Milk jug with cover,6,0.14
54,Stirrup Spout Bottle with Seated Figure,6,0.14
55,Terracotta alabastron (perfume vase),6,0.14
56,Moon flask,6,0.14
57,Water jar,6,0.14
58,Terracotta hydria: kalpis (water jar),6,0.14
59,Terracotta amphora (jar),6,0.14
60,Vase in Meiping Shape,6,0.14
61,Jug with cover,6,0.14
62,Figure Bottle,6,0.14
63,Tea jar with cover,6,0.14
64,Toby jug,5,0.12
65,Terracotta Nolan neck-amphora (jar),5,0.12
66,Cylindrical Vessel,5,0.12
67,Bridge and Spout Bottle,5,0.12
68,Square Bottle,5,0.12
69,Urn,5,0.12
70,"Bottle, Feline Face",5,0.12
71,Terracotta Hadra hydria (water jar),5,0.12
72,Oil Bottle,5,0.12
73,"Bottle, Seated Figure",5,0.12
74,Square vase,5,0.12
75,Terracotta stirrup jar,5,0.12
76,Gourd-shaped bottle,5,0.12
77,Puzzle jug,5,0.12
78,Terracotta squat lekythos (oil flask),5,0.12
79,Covered jar with plum blossoms,5,0.12
80,Flower Vase,5,0.12
81,Covered jar,5,0.12
82,Storage Jar,4,0.1
83,Milk jug,4,0.1
84,Vase with lid,4,0.1
85,Foot Jar,4,0.1
86,Pharmacy jar,4,0.1
87,Beaker,4,0.1
88,Writer's Water Bottle,4,0.1
89,Large Storage Jar (Ōtsubo),4,0.1
90,Meiping vase with floral scrolls,4,0.1
91,Jar with flowers,4,0.1
92,Sake Bottle (Tokkuri),4,0.1
93,Covered jar with birds and flowers,4,0.1
94,Water Pot,4,0.1
95,Hot milk jug,4,0.1
96,Flower vase,4,0.1
97,Minature meiping vase,4,0.1
98,"Bottle, Falcon",4,0.1
99,Covered Vase,4,0.1
100,Miniature Vase,4,0.1
101,Armorial Jug (boccale),4,0.1
102,Gourd-Shaped Bottle,4,0.1
103,Single Spout Bottle,4,0.1
104,Prunus Vase,4,0.1
105,Square vase with scenes of four seasons,4,0.1
106,Vase with handles,4,0.1
107,Apothecary vase (vaso da farmacia),3,0.07
108,Covered jar with floral pattern,3,0.07
109,Covered jar with flowers,3,0.07
110,Amphoriskos,3,0.07
111,Meiping vase with flowers,3,0.07
112,Double-chambered bottle,3,0.07
113,Maebyeong,3,0.07
114,Terracotta oinochoe: chous (jug),3,0.07
115,Vase with dragons,3,0.07
116,Flower Pot,3,0.07
117,Pilgrim Bottle,3,0.07
118,Small Jar,3,0.07
119,Toilet jar with cover,3,0.07
120,Vase with Figures in Landscape,3,0.07
121,Figure Jar,3,0.07
122,Storage Jar (Albarello),3,0.07
123,Cream Pitcher,3,0.07
124,Lidded pharmacy jar with the personification of Fortuna,3,0.07
125,Stirrup Spout Bottle with Figures,3,0.07
126,Vase (vaso),3,0.07
127,Covered Ewer,3,0.07
128,Armorial jug (boccale),3,0.07
129,Terracotta rhyton (vase for libations or drinking),3,0.07
130,Bottle with Bulbous Neck,3,0.07
131,Spouted Vessel,3,0.07
132,Amphora with dragon-shaped handles,3,0.07
133,Vase with lions,3,0.07
134,Double Chambered Bottle,3,0.07
135,Vase with floral patterns,3,0.07
136,Large Jar,3,0.07
137,Figure Vessel,3,0.07
138,Miniature meiping vase,3,0.07
139,Vessel with mythological scene,3,0.07
140,Minature vase,3,0.07
141,Small Jar (Guan),3,0.07
142,Square vase with birds and flowers,3,0.07
143,Hexagonal vase,3,0.07
144,Water Bottle,3,0.07
145,Sake bottle,3,0.07
146,Pilgrim Flask,3,0.07
147,Jar (Hu),3,0.07
148,Miniature Bottle,3,0.07
149,Jar with four lugs,3,0.07
150,Black-topped Red Ware Beaker,3,0.07
151,Jar with floral pattern,3,0.07
152,Urpu (jar),3,0.07
153,Square vase with flowers of four seasons,3,0.07
154,Vase with immortals,3,0.07
155,Square Vase,3,0.07
156,Large Vase,3,0.07
157,Gourd-shaped vase,3,0.07
158,Vase with landscape scenes,3,0.07
159,Ewer (Brocca),2,0.05
160,Covered ewer,2,0.05
161,Bottle for Sweets,2,0.05
162,Vase with scenes and poems from Farming and Weaving,2,0.05
163,Wine Ewer with Lid,2,0.05
164,Terracotta pithoid jar,2,0.05
165,One-handled storage jar (albarello),2,0.05
166,Stirrup Spout Bottle with Felines,2,0.05
167,Portrait Head Bottle,2,0.05
168,Pilgrim bottle with cover,2,0.05
169,Covered urn with geometric decoration,2,0.05
170,Vase decorated with blossoming plum,2,0.05
171,Vase with Flowers,2,0.05
172,Terracotta situla (bucket),2,0.05
173,"Bottle, Anthropomorphic Crab",2,0.05
174,Covered jar with floral patterns,2,0.05
175,Covered jar with lions,2,0.05
176,Terracotta guttus (flask with handle and vertical spout),2,0.05
177,Squat lekythos,2,0.05
178,Jar decorated with auspicious characters amid plants,2,0.05
179,Askos in the form of an animal,2,0.05
180,Epichysis,2,0.05
181,"Bottle, Death Scene (?)",2,0.05
182,Double Spout and Bridge Bottle with Feline and Bird,2,0.05
183,Mallet-shaped vase,2,0.05
184,Jug with Assyrian-inspired decoration,2,0.05
185,Toilet jar,2,0.05
186,Vase with ladies and boys,2,0.05
187,Pitcher (Hu),2,0.05
188,Bottle cooler,2,0.05
189,Jar with dragon,2,0.05
190,Apothecary jar (orciuolo),2,0.05
191,Meiping vase with birds and flowers,2,0.05
192,Terracotta pelike (jar),2,0.05
193,Globular Jar,2,0.05
194,Vase with figural scene,2,0.05
195,Terracotta aryballos (oil flask),2,0.05
196,Wall Vase,2,0.05
197,Miniature jar,2,0.05
198,Stirrup Spout Bottle with Deer,2,0.05
199,Face Jug,2,0.05
200,Jar with lid,2,0.05
201,Terracotta hydria (water jar),2,0.05
202,Club-shaped vase,2,0.05
203,Meiping vase with dragon,2,0.05
204,Paccha (ritual vessel),2,0.05
205,Maebyeong (plum bottle) decorated with cranes and clouds,2,0.05
206,Tuber-inspired stirrup-spout bottle,2,0.05
207,Apothecary bottle (fiasca da farmacia),2,0.05
208,Bridge and Spout Bottle in Bird Form,2,0.05
209,Harvest jug,2,0.05
210,Bottle with Incised Designs,2,0.05
211,Miniature Jar,2,0.05
212,Bottle (Florero),2,0.05
213,Black-topped red ware beaker,2,0.05
214,Scent bottle in the form of a monk,2,0.05
215,Two-Handled Jar with Stag,2,0.05
216,Vase with coiling dragon,2,0.05
217,Terracotta globular flask,2,0.05
218,Tulip Vase,2,0.05
219,Jar with immortals,2,0.05
220,Warrior Bottle,2,0.05
221,Vase in the shape of an ancient ritual beaker (gu),2,0.05
222,Bird Jar,2,0.05
223,"Jar, Fat Figure",2,0.05
224,Stirrup-Spout Bottle,2,0.05
225,Stirrup Spout Bottle with Warrior,2,0.05
226,Vase with Butterflies,2,0.05
227,Flask with molded decoration,2,0.05
228,"Bottle, Sleeping Figure",2,0.05
229,Vase with Coiling Dragon,2,0.05
230,Vase with stopper,2,0.05
231,Minature bottle vase,2,0.05
232,Book flask,2,0.05
233,Double gourd vase,2,0.05
234,Terracotta amphoriskos (oil flask),2,0.05
235,Wall vase,2,0.05
236,Miniature Jar with Cover,2,0.05
237,"""Alhambra"" vase with lid",2,0.05
238,Lidded jar,2,0.05
239,Apothecary Jar,2,0.05
240,Jar (Tsubo) with Chrysanthemums,2,0.05
241,"Meiping vase with peach, pomegranade, and fingered citron",2,0.05
242,Lobed bottle vase,2,0.05
243,"Bottle, Geometric Designs",2,0.05
244,Square Flask,2,0.05
245,Vase with Women Enjoying Scholarly Pursuits,2,0.05
246,Jar with Female Rider,2,0.05
247,Vase decorated with flowers,2,0.05
248,Jar in the shape of bronze container (hu),2,0.05
249,Ampulla (Flask) of Saint Menas,2,0.05
250,Vase with Garden Scene,2,0.05
251,"Two-eared jar, Jun ware",2,0.05
252,Vase with flower and rock,2,0.05
253,Jar with two lugs,2,0.05
254,Milk pot,2,0.05
255,Whistling Stirrup Spout Bottle with Figure,2,0.05
256,Elephant-head vase (vase à tête d'éléphant),2,0.05
257,Milk pot with cover,2,0.05
258,Vase with relief decoration of figures,2,0.05
259,Perfume vase,2,0.05
260,Stirrup Spout Bottle with Portrait Head,2,0.05
261,Oil bottle decorated with peony leaves,2,0.05
262,Miniature Jar with Two Handles,2,0.05
263,Long-Necked Bottle,2,0.05
264,Terracotta spindle bottle,2,0.05
265,Sake Bottle (Tokkuri) in the Shape of an Eggplant,2,0.05
266,Rosewater jug,2,0.05
267,Vase with Basket of Auspicious Flowers,2,0.05
268,Terracotta neck-amphora (jar) with twisted handles,2,0.05
269,Stirrup spout bottle with dignitary figure,2,0.05
270,Freshwater Jar (Mizusashi),2,0.05
271,Jar with Writing,2,0.05
272,Wine jar (Orcio da vino),2,0.05
273,Melon Shaped Bottle,2,0.05
274,Geometric Pattern Bottle,2,0.05
275,Bottle with stopper,2,0.05
276,Single Spout Painted Jar,2,0.05
277,Terracotta jar,2,0.05
278,Covered jar with baskets of flowers,2,0.05
279,Hexagonal vase with lion-head handles,2,0.05
280,Bottle with portrait head,2,0.05
281,Screw-top jar (Schraubflasche),2,0.05
282,Terracotta loutrophoros (ceremonial vase for water),2,0.05
283,Stirrup Spout Bottle with Ai-Apec,2,0.05
284,Jar with Handles,2,0.05
285,Bird Warrior Bottle,2,0.05
286,Vase with butterflies and flowers,2,0.05
287,Bottle vase with dragon,2,0.05
288,Apothecary bottle,2,0.05
289,Small Vase,2,0.05
290,Ewer with Cover,2,0.05
291,"Vase, miniature",2,0.05
292,Water jug,2,0.05
293,Footed Urn,2,0.05
294,Vase with figures,2,0.05
295,Vase with figures in a landscape,2,0.05
296,Jar decorated with dragons,2,0.05
297,Wine container (hu),2,0.05
298,Spill vase,2,0.05
299,Storage jar (albarello),2,0.05
300,Ovoid Jar (Hu),2,0.05
301,Ewer (Schnabelkanne),2,0.05
302,Bottle cooler (seau à bouteille),2,0.05
303,Large jar decorated with peonies,2,0.05
304,Spouted Bottle,2,0.05
305,Spill Vase,2,0.05
306,Creamer,2,0.05
307,Head jar,2,0.05
308,Double gourd bottle,2,0.05
309,"Bottle, Figure Showing Tunic",2,0.05
310,Stirrup Spout Bottle with Tattoed Head,1,0.02
311,Single Spout Bottle with Incised Rings,1,0.02
312,Ring-Shaped Ewer,1,0.02
313,Ewer with 'Tughra-Illuminator' Style Decoration,1,0.02
314,Blackware Vessel with Incised Patterns,1,0.02
315,Moon flask with Japanese woman,1,0.02
316,Vase with Warrior,1,0.02
317,Two-handled vase,1,0.02
318,Bottle with Daoist Immortals,1,0.02
319,Jar with Spiral Decoration and Cross Hatching,1,0.02
320,Vase soliflore,1,0.02
321,Flask with Medallion,1,0.02
322,Jug with portrait of Frederick the Great,1,0.02
323,Vase with dragon amid clouds,1,0.02
324,Vase with ladies and plants,1,0.02
325,Sake bottle with flower medallions,1,0.02
326,Jar for Sweets,1,0.02
327,Apothecary Jar with Running Hares and a Dog,1,0.02
328,Animal-Spouted Pitcher,1,0.02
329,Spout-and-bridge bottle with feline face,1,0.02
330,Handled Vase,1,0.02
331,"Bottle, Feline face",1,0.02
332,Pilgrim vase,1,0.02
333,Monkey Bottle,1,0.02
334,Red and white floral pattern moon flask,1,0.02
335,Jar with lotus scrolls,1,0.02
336,Spouted jar,1,0.02
337,Ewer with Molded Inscriptions and Figures on Horseback,1,0.02
338,Moon flask rust body with central reserve,1,0.02
339,Pierced Jug with Harpies and Sphinxes,1,0.02
340,Jar with Ivory Lid,1,0.02
341,Cuboid vase,1,0.02
342,Large Baluster Jar with Phoenix and Figure of Hawk on Lid,1,0.02
343,Scent bottle in the form of a nun reading a book,1,0.02
344,Stirrup-spout bottle with figure carrying deer,1,0.02
345,Luster-Painted Bottle,1,0.02
346,Jar with Chrysanthemums and Rocks,1,0.02
347,Bottle with floral pattern,1,0.02
348,Unglazed Ewer,1,0.02
349,Jug with Portuguese arms,1,0.02
350,Vase with poems in a panoramic landscape,1,0.02
351,Chamber Pot,1,0.02
352,Pomade pot,1,0.02
353,Vase with poem and mythical beast,1,0.02
354,Bottle with Peony and Rock,1,0.02
355,Vase with deer and pine tree,1,0.02
356,Double Spout and Bridge Bottle with Bird Head,1,0.02
357,Storage jar (albarello) for mostarda,1,0.02
358,"Meiping vase with peaches, pomegranades, and fingered citrons",1,0.02
359,Jar with the emblem of the Order of Saint Augustine,1,0.02
360,Double-End Snake Bottle,1,0.02
361,Small Jar (Kotsubo),1,0.02
362,Large Vase with Cover and Design of Peacocks,1,0.02
363,Vessel with ritual scene,1,0.02
364,Vase in the form of twin fish,1,0.02
365,Stirrup-spout bottle with mouse,1,0.02
366,Bridge and Spout Bottle in Animal Form,1,0.02
367,Ewer with twisted trunk handle,1,0.02
368,Bridge and Double Spout Bottle with Guilloche,1,0.02
369,Animal Bottle,1,0.02
370,Oil bottle decorated with peonies and chrysanthemums,1,0.02
371,Vase with Nine Peaches,1,0.02
372,Recumbent bottle (Yokobe),1,0.02
373,Moon flask with Islamicizing floral motifs,1,0.02
374,Bottle with cloud scrolls,1,0.02
375,Hexagonal vase with stylized phoenix handles,1,0.02
376,Seated Prisoner Single Spout Bottle,1,0.02
377,Jug with Handle,1,0.02
378,Wide-Mouthed Jar (Kame),1,0.02
379,Maiolica: Apothecary jar (albarello),1,0.02
380,Single Spout Monkey Figure Bottle with Strap Handle,1,0.02
381,Ring flask (fiasca d'anello),1,0.02
382,Single Spout Bottle with Resin Paint,1,0.02
383,"Double Spout Bottle, Felines",1,0.02
384,Flask with Molded Decoration,1,0.02
385,Bottle Vase,1,0.02
386,Bottle and cover,1,0.02
387,Vase with Daoist Immortals,1,0.02
388,Barrel,1,0.02
389,Small Covered Jar with Design of Cherry Blossoms and Lambrequin Border,1,0.02
390,Moon flask with mosquito motif,1,0.02
391,Globular vessel with twine impressions,1,0.02
392,Pierced Blue Pot with Animals and Vegetal Scroll,1,0.02
393,Ewer with Filter,1,0.02
394,Jug with Finely-Dressed Woman,1,0.02
395,Vase with Lion-Shaped Handles and Cranes amid Clouds,1,0.02
396,Vase with Cover,1,0.02
397,Vase decorated with cranes amid clouds,1,0.02
398,Jar with scene of Wang Xizhi (303–361) watching geese,1,0.02
399,Freshwater jar,1,0.02
400,Vase with Magnolias,1,0.02
401,"Bottle, Falcon Head",1,0.02
402,Vase in the shape of a gourd,1,0.02
403,Bird jar,1,0.02
404,Sake bottle with chrysanthemums,1,0.02
405,Ewer in the Form of a Phoenix,1,0.02
406,Bottle with caiman,1,0.02
407,Jar in Meiping Shape with Incised Floral Design,1,0.02
408,Moon-Shaped Bottle,1,0.02
409,Sake Bottle in the Shape of a Gourd,1,0.02
410,Water Jar with Plum Tree,1,0.02
411,Large Turquoise Jar,1,0.02
412,Miniature vase with floral medallions,1,0.02
413,Ewer with quatrefoil motifs,1,0.02
414,"Jar, Geometric Pattern",1,0.02
415,Owl Bottle,1,0.02
416,Squared Jar with Cover (Fanghu),1,0.02
417,Covered bean pot,1,0.02
418,Jar with floral sprays,1,0.02
419,Pelike,1,0.02
420,Bottle with flattened side,1,0.02
421,Covered ewer with floral patterns,1,0.02
422,Bottle with fang motif,1,0.02
423,Pharmacy bottle,1,0.02
424,Three-Cornered Bottle,1,0.02
425,Jar with Ducks in Lotus Pond,1,0.02
426,Urn (cachepot),1,0.02
427,Stirrup spout bottle with figure,1,0.02
428,Jar with scholars and crane,1,0.02
429,Ewer with female figure,1,0.02
430,Vase (Hu),1,0.02
431,Kundika (Long-Necked Bottle),1,0.02
432,Wine Jug,1,0.02
433,Twin-fish vase,1,0.02
434,Bottle Depicting Storks in Blue and Yellow on a White Background,1,0.02
435,Jar (Tsubo) with Four Loop Handles and Flower Medallions,1,0.02
436,Cake Jar,1,0.02
437,Double-spout bottle with shark,1,0.02
438,Terracotta lydion (perfume jar),1,0.02
439,Ewer with bird and berry motif,1,0.02
440,Cylindrical vase,1,0.02
441,"Wine jar (Guan), Cizhou ware",1,0.02
442,Gourd vase,1,0.02
443,Single Spout Bottle with Strap Handle and Face,1,0.02
444,Vase in Shape of Ancient Bronze Vessel,1,0.02
445,Vase with Poems Composed by the Qianlong Emperor,1,0.02
446,Small bottle-vase,1,0.02
447,Vase with cover (vase urne antique),1,0.02
448,Milk pitcher,1,0.02
449,Jar decorated with flowers and insects,1,0.02
450,Stirrup-spout Bottle,1,0.02
451,Double Spout and Bridge Bottle with Feline,1,0.02
452,Maebyeong with chrysanthemum decoration,1,0.02
453,Olive-green ground vase with pâte-sur-pâte decoration,1,0.02
454,Jar with Zoomorphic Handle and Spout,1,0.02
455,Vase with poetric scenes,1,0.02
456,Vase with ring handles,1,0.02
457,Jar with Four Lug Handles,1,0.02
458,Terracotta bottle,1,0.02
459,"Pyriform vase, possibly an imitation of Song Guan ware",1,0.02
460,Bottle with Lion,1,0.02
461,Vase with Women’s Activities,1,0.02
462,Feline Bottle,1,0.02
463,Stirrup-spout bottle with mountain sacrifice scene,1,0.02
464,Jar with Basket of Auspicious Flowers,1,0.02
465,Terracotta guttus (flask with handle and verticle spout),1,0.02
466,Vase in the form of a camel,1,0.02
467,Funerary Urn,1,0.02
468,Vase with equestrian figure in landscape,1,0.02
469,Figure jar,1,0.02
470,Ewer with makara spout,1,0.02
471,Flower vase (cuvette à fleurs courteille),1,0.02
472,"Vessel, Seated Deities",1,0.02
473,Four-handled vase,1,0.02
474,Vase with scholars in a garden,1,0.02
475,Bottle with Bulb-Shaped Neck,1,0.02
476,Jar with Abstract Decoration,1,0.02
477,Oblong Single Spout Bottle,1,0.02
478,Double Gourd Vessel,1,0.02
479,Monumental vase,1,0.02
480,Terracotta oinochoe: olpe (jug),1,0.02
481,Luster Jar with Hares (?) and Inscribed Words,1,0.02
482,Apothecary Vase (vaso da farmacia),1,0.02
483,Stirrup-spout bottle with decapitation scene,1,0.02
484,Jar with Lug Handles,1,0.02
485,Orb vase with gold fern motif,1,0.02
486,Vase with Scenes of Daily Life,1,0.02
487,Flask-shaped bottle,1,0.02
488,Pail‑shaped freshwater jar (Onioke mizusashi),1,0.02
489,Moon flask with fretwork center,1,0.02
490,Armorial Jug (vaso),1,0.02
491,Kyathos,1,0.02
492,Vase with Depiction of Bugaku Dancer,1,0.02
493,Vase with green and gold decoration on white,1,0.02
494,Covered Cylinderical Jar,1,0.02
495,Vase with archaistic pattern,1,0.02
496,"Vase with peaches, pomegranates, and fingered citrons",1,0.02
497,Small terracotta amphora (jar),1,0.02
498,Bottle vase with birds,1,0.02
499,Hexagonal Sake Ewer with Landscape Design,1,0.02
500,Stirrup Spout Bottle with Serpent,1,0.02
501,Flask with face,1,0.02
502,Terracotta neck-amphora (jar) of Panathenaic shape,1,0.02
503,Double spout and bridge bottle,1,0.02
504,Pedestal jar with handle and lid,1,0.02
505,Vase with animal-mask handles,1,0.02
506,Sake Bottle (Tokkuri) with Auspicious Patterns,1,0.02
507,Column-krater,1,0.02
508,Hot milk jug with cover,1,0.02
509,Bottle with a thistle medallion,1,0.02
510,Long-Necked Bottle with Design of Chinese Children Playing Outdoors,1,0.02
511,Vase with Dragons and Waves,1,0.02
512,Runners Bottle,1,0.02
513,Moon flask with stylized floral decoration,1,0.02
514,Spout-and-bridge bottle with fox,1,0.02
515,Ewer with gold floral motifs,1,0.02
516,Vase with ladies,1,0.02
517,Vase with mushrooms,1,0.02
518,Small Jar (Kotsubo) with Relief Plum- Blossom Patterns,1,0.02
519,Bird-shaped vessel,1,0.02
520,Vase with Poet Zhou Dunyi,1,0.02
521,Jar with Thistle,1,0.02
522,"Double Spout Bottle, Bird",1,0.02
523,Vase with Scrolling Vines,1,0.02
524,Ewer in Shape of Tibetan Monk’s Cap,1,0.02
525,Octagonal Jar with Decoration of Flowering Cherry and Chrysanthemum,1,0.02
526,Jar with animals and flowers,1,0.02
527,Vase with cranes and peaches,1,0.02
528,Jar with figures in a garden,1,0.02
529,Jar with abstract floral design,1,0.02
530,Covered slop jar,1,0.02
531,Vase in the Form of a Double Gourd,1,0.02
532,Incised Painted Jar with Single Spout,1,0.02
533,Flask-shaped bottle decorated with peonies,1,0.02
534,Terracotta neck-amphora (storage jar),1,0.02
535,Meiping vase with plum blossoms and bamboo,1,0.02
536,Jug with Eagle,1,0.02
537,Bottle with Pine Tree,1,0.02
538,Bottle with Dragons,1,0.02
539,Pharmacy jar with cover,1,0.02
540,Tobacco Jar,1,0.02
541,Jar with Two Loop Handles (Hu),1,0.02
542,Vase with cover (probably vase à bâtons rompus),1,0.02
543,Vase with birds and portrait,1,0.02
544,Vase in the form of an archaic bronze vessel,1,0.02
545,Spout-and-bridge bottle with funerary procession,1,0.02

In [26]:
# objectname_summary.to_csv("objectname_summary_2.csv", index=False)

In [29]:
# df_objectname_summary_2 = pd.read_csv("objectname_summary_2.csv")

In [ ]:
group_counts_case_insensitive = (
    df_objectname_summary_2["objectName_Group"]
    .astype("string")
    .str.strip()
    .replace("", pd.NA)
    .dropna()
    .str.casefold()
    .value_counts()
    .rename_axis("objectName_Group_normalized")
    .reset_index(name="count")
)

with pd.option_context("display.max_rows", None, "display.max_columns", None, "display.max_colwidth", None):
    display(group_counts_case_insensitive)

            objectName_Group_normalized  count
0                                   jar     54
1                                  vase     35
2                                bottle     26
3                                   jug     24
4                                   pot     18
5                                 flask     13
6                               amphora     13
7                                vessel      9
8                                beaker      8
9                                  ewer      6
10                                askos      6
11                                  urn      6
12                              pitcher      5
13                            aryballos      5
14                               krater      5
15                               hydria      5
16                               juglet      4
17                             oinochoe      3
18                           alabastron      3
19                                  lid      3
20                                 lamp      3
21                             lekythos      2
22                          neck-pelike      1
23                              brazier      1
24                     tazza with cover      1
25                      seal impression      1
26                               bucket      1
27                                kendi      1
28                            plemochoe      1
29                          ring-kernos      1
30                                  oon      1
31                                kylix      1
32                             nestoris      1
33                           pen washer      1
34                                dinos      1
35                           saltcellar      1
36                         glass cooler      1
37                           aquamanile      1
38                                 kero      1
39              holder for magic straws      1
40                         brush holder      1
41                               lydion      1
42                         thymiaterion      1
43                 statuette of a woman      1
44                              aidoion      1
45                               censer      1
46                                caddy      1
47                              ampulla      1
48                               dipper      1
49                              kyathos      1
50                               situla      1
51  rhyton in the form of a lamb's head      1
52                             strainer      1
53                          bottle vase      1
54                            albarello      1
55                               figure      1
56                          water coupe      1
57                          amphoriskos      1
58                               pelike      1
59                               goblet      1
60                            coffeepot      1
61                               guttus      1
62                              skyphos      1
63                               tripod      1
64                         loutrophoros      1
65                               waster      1
66                              tumbler      1
67                              stamnos      1
68                               rhyton      1
69                             gallipot      1
70                            epichysis      1
71                                  toy      1
72                              ceramic      1
73                        lebes gamikos      1
74                              lekanis      1
75                             kalathos      1
76                              inkwell      1
77                              roundel      1
78                                 mold      1
79                                 olpe      1

In [ ]:
# keywords = ["mold", "toy", "tumbler", "goblet", "figure", "coffeepot"]  # add/remove terms here

# keywords = ["dipper", "ink", "statuette", "tazza"]
# keywords = ["trumbler"]
# keywords = ["aidoion"]
# keywords = ["lamp"]
# keywords = ["lekanis"]
# keywords = ["tripod"]
# keywords = ["kylix", "syphos", "dinos", "lekanis", "coupe"]
# keywords = ["bottle vase", "magic straws"]
# keywords = ["waster", "roundel", "aidoion", "oon", "magic"]
# keywords = ["hydria"]
keywords = ["kalathos"]

pattern = "|".join(map(re.escape, keywords))

df.loc[
    df["objectName"].astype("string").str.strip().str.lower().str.contains(pattern, na=False),
    ["objectID", "title", "department", "objectName"],
].sort_values("objectID")

,objectID,title,department,objectName
3901,248515,Terracotta kalathos (vase with flaring lip),Greek and Roman Art,Kalathos

In [ ]:
object_ids = (
    df.loc[
        df["objectName"].astype("string").str.strip().str.lower().str.contains(pattern, na=False),
        "objectID",
    ]
    .dropna()
    .astype(int)
    .drop_duplicates()
    .sort_values()
    .tolist()
)

object_ids

[194246, 241273, 255580, 308521]